package com.example.demo.student;

import java.time.LocalDate;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import antlr.collections.List;


// It is used as a source of bean definitions. 
// It is a class-level annotation.
@Configuration
public class StudentConfig {
	
	// Inject StudentRepository
	@Bean
	CommandLineRunner commandLineRunner(StudentRepository studentRepository) {
		
		return args -> {
			
			// Removed Id because it will be generated by Database
			Student akram = new Student(
					"Akram", 
					"Akram@gmail.com", 
					LocalDate.of(1984, 05, 01));

			
			Student alex = new Student(
					"alex", 
					"alex@gmail.com", 
					LocalDate.of(1981, 05, 01));
			
			Student pardis = new Student(
					"pardis", 
					"paradis@gmail.com", 
					LocalDate.of(1988, 02, 9));
			
			
			
			studentRepository.save(akram);
		};
		
	}

}
